services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${ POSTGRES_USER }
      POSTGRES_PASSWORD: ${ POSTGRES_PASSWORD }
      POSTGRES_DB: ${ POSTGRES_DB }
    volumes:
#      - ./scripts/:/docker-entrypoint-initdb.d/
      - /large/data4/cookbook/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
    restart: unless-stopped
    ports:
      - 5437:5432

  web:
    build: ./recipes
    command: gunicorn recipes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /large/data4/cookbook/static:/app/static
      - /large/data4/cookbook/media:/app/media
      - /large/data4/cookbook/log:/app/log
    env_file:
      - ./recipes/.env
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - /large/data4/cookbook/static:/app/static
      - /large/data4/cookbook/media:/app/media
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - web
    restart: unless-stopped
